In [1]:
from get_data import GetData
import pandas as pd

In [2]:
hackney = GetData('Hackney')
lambeth = GetData('lambeth')
westminter = GetData('westminster')
london = GetData('london')

In [3]:
locations_list = [hackney, lambeth, westminter]

In [4]:
id_list = []
for i in locations_list:
    authority_id = i.get_local_authority_data(get_id= True)
    id_list.append(authority_id)
print(id_list)

['12', '22', '33']

In [5]:
london.get_pollution_data(12, [2018])

,species_code,species_desc,objective_name,value,site_name,year,latitude,longitude
0,DUST,PM10 (not reference equiv.),40 ug/m3 as an annual mean,24,Hackney - Old Street,2018,51.526454,-0.08491
1,DUST,PM10 (not reference equiv.),"50 ug/m3 as a 24 hour mean, not to be exceeded...",2,Hackney - Old Street,2018,51.526454,-0.08491
2,DUST,PM10 (not reference equiv.),Capture Rate (%),89,Hackney - Old Street,2018,51.526454,-0.08491
3,NO2,Nitrogen Dioxide,"200 ug/m3 as a 1 hour mean, not to be exceeded...",0,Hackney - Old Street,2018,51.526454,-0.08491
4,NO2,Nitrogen Dioxide,40 ug/m3 as an annual mean,50,Hackney - Old Street,2018,51.526454,-0.08491
5,NO2,Nitrogen Dioxide,Capture Rate (%),99,Hackney - Old Street,2018,51.526454,-0.08491
6,O3,Ozone,"100 ug/m3 as an 8 hour mean, not to be exceede...",5,Hackney - Old Street,2018,51.526454,-0.08491
7,O3,Ozone,Capture Rate (%),99,Hackney - Old Street,2018,51.526454,-0.08491
8,PM10,PM10 Particulate,40 ug/m3 as an annual mean,22,Hackney - Old Street,2018,51.526454,-0.08491
9,PM10,PM10 Particulate,"50 ug/m3 as a 24 hour mean, not to be exceeded...",2,Hackney - Old Street,2018,51.526454,-0.08491
10,PM10,PM10 Particulate,Capture Rate (%),82,Hackney - Old Street,2018,51.526454,-0.08491

In [5]:
london.get_daily_pollution_stats(id_list)

,species_code,site_name,air_quality_index,air_quality_band,site_code
0,NO2,Hackney - Old Street,1,Low,HK6
1,O3,Hackney - Old Street,2,Low,HK6
2,PM10,Hackney - Old Street,1,Low,HK6
3,PM10,Lambeth - Brixton Road,2,Low,LB4
4,NO2,Lambeth - Bondway Interchange,2,Low,LB5
5,PM10,Lambeth - Bondway Interchange,3,Low,LB5
6,SO2,Lambeth - Bondway Interchange,1,Low,LB5
7,NO2,Lambeth - Streatham Green,1,Low,LB6
8,PM10,Lambeth - Streatham Green,1,Low,LB6
9,NO2,Westminster - Ebury Street (Grosvenor),1,Low,GV1
10,NO2,Westminster - Marylebone Road,2,Low,MY1
11,O3,Westminster - Marylebone Road,2,Low,MY1
12,SO2,Westminster - Marylebone Road,1,Low,MY1
13,PM10,Westminster - Marylebone Road FDMS,2,Low,MY7
14,PM25,Westminster - Marylebone Road FDMS,1,Low,MY7
15,NO2,Westminster - Strand (Northbank BID),2,Low,NB1
16,NO2,Westminster - Horseferry Road,1,Low,WM0
17,PM10,Westminster - Horseferry Road,1,Low,WM0
18,NO2,Westminster - Oxford Street,2,Low,WM6
19,PM10,Westminster - Oxford Street,2,Low,WM6
20,NO2,Westminster - Buckingham Palace Road,1,Low,WMA
21,NO2,Westminster - Oxford Street East,1,Low,WMB
22,PM10,Westminster - Oxford Street East,1,Low,WMB
23,NO2,Westminster - Cavendish Square,2,Low,WMC
24,PM10,Westminster - Cavendish Square,2,Low,WMC